// <auto-generated />
using System;
using LuzDeVida.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuzDeVida.API.Migrations.LuzDeVidaDb
{
    [DbContext(typeof(LuzDeVidaDbContext))]
    partial class LuzDeVidaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuzDeVida.API.Models.app_user", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("supporter");

                    b.Property<int?>("supporter_id")
                        .HasColumnType("int");

                    b.HasKey("user_id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("supporter_id");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("LuzDeVida.API.Models.donation", b =>
                {
                    b.Property<int>("donation_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("campaign_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("channel_source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("created_by_partner_id")
                        .HasColumnType("int");

                    b.Property<string>("currency_code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("donation_date")
                        .HasColumnType("date");

                    b.Property<string>("donation_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("estimated_value")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("impact_unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("is_recurring")
                        .HasColumnType("bit");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("referral_post_id")
                        .HasColumnType("int");

                    b.Property<int>("supporter_id")
                        .HasColumnType("int");

                    b.HasKey("donation_id")
                        .HasName("PK__donation__296B91DC41AB1A05");

                    b.HasIndex("created_by_partner_id");

                    b.HasIndex("referral_post_id");

                    b.HasIndex("supporter_id");

                    b.ToTable("donations");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.donation_allocation", b =>
                {
                    b.Property<int>("allocation_id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("allocation_date")
                        .HasColumnType("date");

                    b.Property<string>("allocation_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("amount_allocated")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("donation_id")
                        .HasColumnType("int");

                    b.Property<string>("program_area")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("safehouse_id")
                        .HasColumnType("int");

                    b.HasKey("allocation_id")
                        .HasName("PK__donation__5DFAFF3028F97333");

                    b.HasIndex("donation_id");

                    b.HasIndex("safehouse_id");

                    b.ToTable("donation_allocations");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.education_record", b =>
                {
                    b.Property<int>("education_record_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("attendance_rate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("completion_status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("education_level")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("enrollment_status")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("progress_percent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateOnly?>("record_date")
                        .HasColumnType("date");

                    b.Property<int>("resident_id")
                        .HasColumnType("int");

                    b.Property<string>("school_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("education_record_id")
                        .HasName("PK__educatio__EA4B1D8F82E6ABAD");

                    b.HasIndex("resident_id");

                    b.ToTable("education_records");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.health_wellbeing_record", b =>
                {
                    b.Property<int>("health_record_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("bmi")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool?>("dental_checkup_done")
                        .HasColumnType("bit");

                    b.Property<decimal?>("energy_score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("general_health_score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("height_cm")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool?>("medical_checkup_done")
                        .HasColumnType("bit");

                    b.Property<string>("medical_notes_restricted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("nutrition_score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool?>("psychological_checkup_done")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("record_date")
                        .HasColumnType("date");

                    b.Property<int>("resident_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("sleep_score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("weight_kg")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("health_record_id")
                        .HasName("PK__health_w__B1EEFD8F721197C7");

                    b.HasIndex("resident_id");

                    b.ToTable("health_wellbeing_records");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.home_visitation", b =>
                {
                    b.Property<int>("visitation_id")
                        .HasColumnType("int");

                    b.Property<string>("family_cooperation_level")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("family_members_present")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("follow_up_needed")
                        .HasColumnType("bit");

                    b.Property<string>("follow_up_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location_visited")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("resident_id")
                        .HasColumnType("int");

                    b.Property<bool?>("safety_concerns_noted")
                        .HasColumnType("bit");

                    b.Property<string>("social_worker")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("visit_date")
                        .HasColumnType("date");

                    b.Property<string>("visit_outcome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("visit_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("visitation_id")
                        .HasName("PK__home_vis__9F102772DCCE8D22");

                    b.HasIndex("resident_id");

                    b.ToTable("home_visitations");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.in_kind_donation_item", b =>
                {
                    b.Property<int>("item_id")
                        .HasColumnType("int");

                    b.Property<int>("donation_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("estimated_unit_value")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("intended_use")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("item_category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("item_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("received_condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("unit_of_measure")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("item_id")
                        .HasName("PK__in_kind___52020FDDBBF3F9C3");

                    b.HasIndex("donation_id");

                    b.ToTable("in_kind_donation_items");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.incident_report", b =>
                {
                    b.Property<int>("incident_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("follow_up_required")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("incident_date")
                        .HasColumnType("date");

                    b.Property<string>("incident_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("reported_by")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("resident_id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("resolution_date")
                        .HasColumnType("date");

                    b.Property<bool?>("resolved")
                        .HasColumnType("bit");

                    b.Property<string>("response_taken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("safehouse_id")
                        .HasColumnType("int");

                    b.Property<string>("severity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("incident_id")
                        .HasName("PK__incident__E6C40DA3BE4EC75C");

                    b.HasIndex("resident_id");

                    b.HasIndex("safehouse_id");

                    b.ToTable("incident_reports");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.intervention_plan", b =>
                {
                    b.Property<int>("plan_id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("case_conference_date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("plan_category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("plan_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("resident_id")
                        .HasColumnType("int");

                    b.Property<string>("services_provided")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("target_date")
                        .HasColumnType("date");

                    b.Property<decimal?>("target_value")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.HasKey("plan_id")
                        .HasName("PK__interven__BE9F8F1D22BEEAA3");

                    b.HasIndex("resident_id");

                    b.ToTable("intervention_plans");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.ml_donor_churn_prediction", b =>
                {
                    b.Property<int>("supporter_id")
                        .HasColumnType("int");

                    b.Property<double>("churn_risk_score")
                        .HasColumnType("float");

                    b.Property<string>("display_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("risk_tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("scored_at")
                        .HasColumnType("datetime");

                    b.HasKey("supporter_id");

                    b.ToTable("ml_donor_churn_predictions", (string)null);
                });

            modelBuilder.Entity("LuzDeVida.API.Models.ml_resident_risk_prediction", b =>
                {
                    b.Property<int>("resident_id")
                        .HasColumnType("int");

                    b.Property<string>("case_control_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("internal_code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("risk_score")
                        .HasColumnType("float");

                    b.Property<string>("risk_tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("safehouse_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("scored_at")
                        .HasColumnType("datetime");

                    b.HasKey("resident_id");

                    b.ToTable("ml_resident_risk_predictions", (string)null);
                });

            modelBuilder.Entity("LuzDeVida.API.Models.ml_social_media_prediction", b =>
                {
                    b.Property<int>("post_id")
                        .HasColumnType("int");

                    b.Property<string>("content_topic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("conversion_probability")
                        .HasColumnType("float");

                    b.Property<string>("conversion_tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("platform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("post_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("scored_at")
                        .HasColumnType("datetime");

                    b.HasKey("post_id");

                    b.ToTable("ml_social_media_predictions", (string)null);
                });

            modelBuilder.Entity("LuzDeVida.API.Models.partner", b =>
                {
                    b.Property<int>("partner_id")
                        .HasColumnType("int");

                    b.Property<string>("contact_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("end_date")
                        .HasColumnType("date");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partner_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("partner_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("role_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("start_date")
                        .HasColumnType("date");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("partner_id")
                        .HasName("PK__partners__576F1B2759405C10");

                    b.ToTable("partners");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.partner_assignment", b =>
                {
                    b.Property<int>("assignment_id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("assignment_end")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("assignment_start")
                        .HasColumnType("date");

                    b.Property<bool?>("is_primary")
                        .HasColumnType("bit");

                    b.Property<int>("partner_id")
                        .HasColumnType("int");

                    b.Property<string>("program_area")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("responsibility_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("safehouse_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("assignment_id")
                        .HasName("PK__partner___DA891814B1C85E0B");

                    b.HasIndex("partner_id");

                    b.HasIndex("safehouse_id");

                    b.ToTable("partner_assignments");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.process_recording", b =>
                {
                    b.Property<int>("recording_id")
                        .HasColumnType("int");

                    b.Property<bool?>("concerns_flagged")
                        .HasColumnType("bit");

                    b.Property<string>("emotional_state_end")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("emotional_state_observed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("follow_up_actions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("interventions_applied")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes_restricted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("progress_noted")
                        .HasColumnType("bit");

                    b.Property<bool?>("referral_made")
                        .HasColumnType("bit");

                    b.Property<int>("resident_id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("session_date")
                        .HasColumnType("date");

                    b.Property<int?>("session_duration_minutes")
                        .HasColumnType("int");

                    b.Property<string>("session_narrative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("session_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("social_worker")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("recording_id")
                        .HasName("PK__process___0C5B24E57E347821");

                    b.HasIndex("resident_id");

                    b.ToTable("process_recordings");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.public_impact_snapshot", b =>
                {
                    b.Property<int>("snapshot_id")
                        .HasColumnType("int");

                    b.Property<string>("headline")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("is_published")
                        .HasColumnType("bit");

                    b.Property<string>("metric_payload_json")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("published_at")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("snapshot_date")
                        .HasColumnType("date");

                    b.Property<string>("summary_text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("snapshot_id")
                        .HasName("PK__public_i__C27CFBF76A2A959C");

                    b.ToTable("public_impact_snapshots");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.resident", b =>
                {
                    b.Property<int>("resident_id")
                        .HasColumnType("int");

                    b.Property<string>("age_upon_admission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("assigned_social_worker")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("birth_status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("case_category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("case_control_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("case_status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("current_risk_level")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("date_case_study_prepared")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("date_closed")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("date_colb_obtained")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("date_colb_registered")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("date_enrolled")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("date_of_admission")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("date_of_birth")
                        .HasColumnType("date");

                    b.Property<bool?>("family_indigenous")
                        .HasColumnType("bit");

                    b.Property<bool?>("family_informal_settler")
                        .HasColumnType("bit");

                    b.Property<bool?>("family_is_4ps")
                        .HasColumnType("bit");

                    b.Property<bool?>("family_parent_pwd")
                        .HasColumnType("bit");

                    b.Property<bool?>("family_solo_parent")
                        .HasColumnType("bit");

                    b.Property<bool?>("has_special_needs")
                        .HasColumnType("bit");

                    b.Property<string>("initial_case_assessment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("initial_risk_level")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("internal_code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("is_pwd")
                        .HasColumnType("bit");

                    b.Property<string>("length_of_stay")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("notes_restricted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("place_of_birth")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("present_age")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pwd_type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("referral_source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("referring_agency_person")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("reintegration_status")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("reintegration_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("religion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("safehouse_id")
                        .HasColumnType("int");

                    b.Property<string>("sex")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("special_needs_diagnosis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("sub_cat_at_risk")
                        .HasColumnType("bit");

                    b.Property<bool?>("sub_cat_child_labor")
                        .HasColumnType("bit");

                    b.Property<bool?>("sub_cat_child_with_hiv")
                        .HasColumnType("bit");

                    b.Property<bool?>("sub_cat_cicl")
                        .HasColumnType("bit");

                    b.Property<bool?>("sub_cat_orphaned")
                        .HasColumnType("bit");

                    b.Property<bool?>("sub_cat_osaec")
                        .HasColumnType("bit");

                    b.Property<bool?>("sub_cat_physical_abuse")
                        .HasColumnType("bit");

                    b.Property<bool?>("sub_cat_sexual_abuse")
                        .HasColumnType("bit");

                    b.Property<bool?>("sub_cat_street_child")
                        .HasColumnType("bit");

                    b.Property<bool?>("sub_cat_trafficked")
                        .HasColumnType("bit");

                    b.HasKey("resident_id")
                        .HasName("PK__resident__A5BC2ECE00C9312B");

                    b.HasIndex("safehouse_id");

                    b.ToTable("residents");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.safehouse", b =>
                {
                    b.Property<int>("safehouse_id")
                        .HasColumnType("int");

                    b.Property<int?>("capacity_girls")
                        .HasColumnType("int");

                    b.Property<int?>("capacity_staff")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("country")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Costa Rica");

                    b.Property<int?>("current_occupancy")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("open_date")
                        .HasColumnType("date");

                    b.Property<string>("province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("safehouse_code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("safehouse_id")
                        .HasName("PK__safehous__BC4083B50113B168");

                    b.ToTable("safehouses");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.safehouse_monthly_metric", b =>
                {
                    b.Property<int>("metric_id")
                        .HasColumnType("int");

                    b.Property<int?>("active_residents")
                        .HasColumnType("int");

                    b.Property<decimal?>("avg_education_progress")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("avg_health_score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("home_visitation_count")
                        .HasColumnType("int");

                    b.Property<int?>("incident_count")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("month_end")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("month_start")
                        .HasColumnType("date");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("process_recording_count")
                        .HasColumnType("int");

                    b.Property<int>("safehouse_id")
                        .HasColumnType("int");

                    b.HasKey("metric_id")
                        .HasName("PK__safehous__13D5DCA4E595EFAB");

                    b.HasIndex("safehouse_id");

                    b.ToTable("safehouse_monthly_metrics");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.social_media_post", b =>
                {
                    b.Property<int>("post_id")
                        .HasColumnType("int");

                    b.Property<int?>("avg_view_duration_seconds")
                        .HasColumnType("int");

                    b.Property<decimal?>("boost_budget_php")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("call_to_action_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("campaign_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("caption_length")
                        .HasColumnType("int");

                    b.Property<int?>("click_throughs")
                        .HasColumnType("int");

                    b.Property<int?>("comments")
                        .HasColumnType("int");

                    b.Property<string>("content_topic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("day_of_week")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("donation_referrals")
                        .HasColumnType("int");

                    b.Property<decimal?>("engagement_rate")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<decimal?>("estimated_donation_value_php")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool?>("features_resident_story")
                        .HasColumnType("bit");

                    b.Property<int?>("follower_count_at_post")
                        .HasColumnType("int");

                    b.Property<int?>("forwards")
                        .HasColumnType("int");

                    b.Property<bool?>("has_call_to_action")
                        .HasColumnType("bit");

                    b.Property<string>("hashtags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("impressions")
                        .HasColumnType("int");

                    b.Property<bool?>("is_boosted")
                        .HasColumnType("bit");

                    b.Property<int?>("likes")
                        .HasColumnType("int");

                    b.Property<string>("media_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("mentions_count")
                        .HasColumnType("int");

                    b.Property<int?>("num_hashtags")
                        .HasColumnType("int");

                    b.Property<string>("platform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("platform_post_id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("post_hour")
                        .HasColumnType("int");

                    b.Property<string>("post_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("post_url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("profile_visits")
                        .HasColumnType("int");

                    b.Property<int?>("reach")
                        .HasColumnType("int");

                    b.Property<int?>("saves")
                        .HasColumnType("int");

                    b.Property<string>("sentiment_tone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("shares")
                        .HasColumnType("int");

                    b.Property<int?>("subscriber_count_at_post")
                        .HasColumnType("int");

                    b.Property<int?>("video_views")
                        .HasColumnType("int");

                    b.Property<int?>("watch_time_seconds")
                        .HasColumnType("int");

                    b.HasKey("post_id")
                        .HasName("PK__social_m__3ED78766F2DFD312");

                    b.ToTable("social_media_posts");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.supporter", b =>
                {
                    b.Property<int>("supporter_id")
                        .HasColumnType("int");

                    b.Property<string>("acquisition_channel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("display_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("first_donation_date")
                        .HasColumnType("date");

                    b.Property<string>("first_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("last_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("organization_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("relationship_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("supporter_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("supporter_id")
                        .HasName("PK__supporte__F3A5770107B35CDA");

                    b.ToTable("supporters");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.app_user", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.supporter", "supporter")
                        .WithMany()
                        .HasForeignKey("supporter_id")
                        .HasConstraintName("FK_app_users_supporters");

                    b.Navigation("supporter");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.donation", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.partner", "created_by_partner")
                        .WithMany("donations")
                        .HasForeignKey("created_by_partner_id")
                        .HasConstraintName("FK_donations_partners");

                    b.HasOne("LuzDeVida.API.Models.social_media_post", "referral_post")
                        .WithMany("donations")
                        .HasForeignKey("referral_post_id")
                        .HasConstraintName("FK_donations_posts");

                    b.HasOne("LuzDeVida.API.Models.supporter", "supporter")
                        .WithMany("donations")
                        .HasForeignKey("supporter_id")
                        .IsRequired()
                        .HasConstraintName("FK_donations_supporters");

                    b.Navigation("created_by_partner");

                    b.Navigation("referral_post");

                    b.Navigation("supporter");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.donation_allocation", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.donation", "donation")
                        .WithMany("donation_allocations")
                        .HasForeignKey("donation_id")
                        .IsRequired()
                        .HasConstraintName("FK_donation_allocations_donations");

                    b.HasOne("LuzDeVida.API.Models.safehouse", "safehouse")
                        .WithMany("donation_allocations")
                        .HasForeignKey("safehouse_id")
                        .IsRequired()
                        .HasConstraintName("FK_donation_allocations_safehouses");

                    b.Navigation("donation");

                    b.Navigation("safehouse");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.education_record", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.resident", "resident")
                        .WithMany("education_records")
                        .HasForeignKey("resident_id")
                        .IsRequired()
                        .HasConstraintName("FK_education_records_residents");

                    b.Navigation("resident");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.health_wellbeing_record", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.resident", "resident")
                        .WithMany("health_wellbeing_records")
                        .HasForeignKey("resident_id")
                        .IsRequired()
                        .HasConstraintName("FK_health_wellbeing_records_residents");

                    b.Navigation("resident");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.home_visitation", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.resident", "resident")
                        .WithMany("home_visitations")
                        .HasForeignKey("resident_id")
                        .HasConstraintName("FK_home_visitations_residents");

                    b.Navigation("resident");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.in_kind_donation_item", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.donation", "donation")
                        .WithMany("in_kind_donation_items")
                        .HasForeignKey("donation_id")
                        .IsRequired()
                        .HasConstraintName("FK_in_kind_donation_items_donations");

                    b.Navigation("donation");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.incident_report", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.resident", "resident")
                        .WithMany("incident_reports")
                        .HasForeignKey("resident_id")
                        .IsRequired()
                        .HasConstraintName("FK_incident_reports_residents");

                    b.HasOne("LuzDeVida.API.Models.safehouse", "safehouse")
                        .WithMany("incident_reports")
                        .HasForeignKey("safehouse_id")
                        .IsRequired()
                        .HasConstraintName("FK_incident_reports_safehouses");

                    b.Navigation("resident");

                    b.Navigation("safehouse");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.intervention_plan", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.resident", "resident")
                        .WithMany("intervention_plans")
                        .HasForeignKey("resident_id")
                        .HasConstraintName("FK_intervention_plans_residents");

                    b.Navigation("resident");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.partner_assignment", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.partner", "partner")
                        .WithMany("partner_assignments")
                        .HasForeignKey("partner_id")
                        .IsRequired()
                        .HasConstraintName("FK_partner_assignments_partners");

                    b.HasOne("LuzDeVida.API.Models.safehouse", "safehouse")
                        .WithMany("partner_assignments")
                        .HasForeignKey("safehouse_id")
                        .HasConstraintName("FK_partner_assignments_safehouses");

                    b.Navigation("partner");

                    b.Navigation("safehouse");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.process_recording", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.resident", "resident")
                        .WithMany("process_recordings")
                        .HasForeignKey("resident_id")
                        .IsRequired()
                        .HasConstraintName("FK_process_recordings_residents");

                    b.Navigation("resident");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.resident", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.safehouse", "safehouse")
                        .WithMany("residents")
                        .HasForeignKey("safehouse_id")
                        .HasConstraintName("FK_residents_safehouses");

                    b.Navigation("safehouse");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.safehouse_monthly_metric", b =>
                {
                    b.HasOne("LuzDeVida.API.Models.safehouse", "safehouse")
                        .WithMany("safehouse_monthly_metrics")
                        .HasForeignKey("safehouse_id")
                        .IsRequired()
                        .HasConstraintName("FK_safehouse_monthly_metrics_safehouses");

                    b.Navigation("safehouse");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.donation", b =>
                {
                    b.Navigation("donation_allocations");

                    b.Navigation("in_kind_donation_items");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.partner", b =>
                {
                    b.Navigation("donations");

                    b.Navigation("partner_assignments");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.resident", b =>
                {
                    b.Navigation("education_records");

                    b.Navigation("health_wellbeing_records");

                    b.Navigation("home_visitations");

                    b.Navigation("incident_reports");

                    b.Navigation("intervention_plans");

                    b.Navigation("process_recordings");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.safehouse", b =>
                {
                    b.Navigation("donation_allocations");

                    b.Navigation("incident_reports");

                    b.Navigation("partner_assignments");

                    b.Navigation("residents");

                    b.Navigation("safehouse_monthly_metrics");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.social_media_post", b =>
                {
                    b.Navigation("donations");
                });

            modelBuilder.Entity("LuzDeVida.API.Models.supporter", b =>
                {
                    b.Navigation("donations");
                });
#pragma warning restore 612, 618
        }
    }
}
